### ISSUE TITLE
github_ref suddenly disappears

### ISSUE THREAD

**Issue by legshort** [getslashdeploy/roadmap#14]
Hi there, I suddenly have this problem and ended up here.

as you can see `ref` which is I used to use `github.ref` from github action is missing from last night, below screenshot is from `echo ${{ toJson(github) }}` on Github Action.

![image](https://user-images.githubusercontent.com/4326608/83515821-f2376d80-a510-11ea-9b1e-68db6fb1cbb1.png)

Also, I checked the Github Deployment detail with id, `sha` and `ref` are same, I think `ref` should be something like `refs/head/master`. 

![image](https://user-images.githubusercontent.com/4326608/83516052-58bc8b80-a511-11ea-98d8-31d297dec8d1.png)

please take a look for me, thanks!

**Comment by assimovt** [comment]
@legshort Sorry for the delay here, we've been busy with some infra work. 

I've checked your issue and it looks like an expected behavior for the way auto-deployments work. When you're deploying manually via `/deploy` command and give it a Git ref (branch, tag, etc.), internally we're looking up its associated SHA.

With an auto-deployment though, we cannot reliably detect the Git ref, since it's just a label and there can be multiple labels pointing to the same Git SHA. All that SlashDeploy does is it receives a GitHub Push event and uses a provided SHA as a ref, which is why you see it in the GitHub Deployment API request.

Let me know what's your use case and perhaps we could find some other solution to your workflow?

**Comment by legshort** [comment]
@assimovt thanks for your comment.
I would like to know which branch is deployed automatically when I setup like this
```
auto_deploy:
      ref: refs\/heads\/dev.+
```

For right now, I couldn't find any solution yet, plz let me know if there is a way to detect the deployed branch.

**Comment by assimovt** [comment]
@legshort we made some improvements and you should now have a correct ref in the payload. Could you please try if it fixes your issue and sorry for the confusion.

**Comment by legshort** [comment]
Yeah now we have a correct github ref, thanks for fixing!

before
![image](https://user-images.githubusercontent.com/4326608/89500819-473b7c80-d7fd-11ea-8729-2b2332810fd4.png)

after
![image](https://user-images.githubusercontent.com/4326608/89500866-56bac580-d7fd-11ea-8401-e3820d43f9ae.png)
